#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in2,    LPot,           sensorPotentiometer)
#pragma config(Sensor, in3,    RPot,           sensorPotentiometer)
#pragma config(Sensor, in4,    AutoPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl4,  RLED,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  YLED,           sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  backLeftIEM,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  frontLeftIEM,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  frontRightIEM,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  backRightIEM,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           LScoop,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RScoop,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armLT,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armLB,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRT,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armRB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Fancy Autonomous
----------------------------------------------------------------------------------------------------*/

//all the wheels stop moving
void still()
{
	motor[frontRight] = motor[backLeft]
	= motor[frontLeft]
	= motor[backRight] = 0;
}

//everything shuts off
void die()
{
	still();
	motor[armLT]	= motor[armLB]
								= motor[armRT]
								= motor[armRB] = 0;
}

float side = 1; //1 for start on right blue side, -1 for left side


//moves the robot forward (f),backward (b),left(l), or right(r)
//distance is in inches
void move(char dir, int speed, int distance)
{
	//assume CW is + and CCW is -
	resetMotorEncoder(backRight);
	resetMotorEncoder(frontRight);
	resetMotorEncoder(backLeft);
	resetMotorEncoder(frontLeft);

	int x = (150/(4*PI))*sqrt(2)*distance;
	switch (dir)
	{
	 case 'f':
	 	while(nMotorEncoder[backRight] > -x)
		{
			motor[frontRight] = motor[backRight]  = -speed;
			motor[frontLeft]  = motor[backLeft] = -speed;
		}
	  break;
	 case 'b':
	 	while(nMotorEncoder[backRight] < x)
		{
			motor[frontRight] = motor[backRight]  = speed;
			motor[frontLeft]  = motor[backLeft] = speed;
		}
		break;
	 case 'r':
	 	while((nMotorEncoder[backRight] > -x))
		{

				motor[frontRight] = motor[backLeft]  = speed;
				motor[frontLeft]  = motor[backRight] = -speed;
		/*	if((abs(nMotorEncoder[frontRight]) - abs(nMotorEncoder[backRight]))<20)
			{
				motor[frontRight] = motor[backLeft]  = speed;
				motor[frontLeft]  = motor[backRight] = -speed;
			}
			else if(abs(nMotorEncoder[backRight])>abs(nMotorEncoder[frontRight]))
			{
				motor[frontRight] = motor[backLeft]  = speed;
				motor[frontLeft]  = -speed;
				motor[backRight] = -speed*0.5;//(1-(abs(nMotorEncoder[frontRight])/abs(nMotorEncoder[backRight])));
			}
			else
			{
				motor[frontRight] = speed*0.5;
				motor[backLeft]  = speed;//(1-(abs(nMotorEncoder[backRight])/abs(nMotorEncoder[frontRight])));
				motor[frontLeft]  = motor[backRight] = -speed;
			}*/

		}
		break;
	 case 'l':
	 	while(nMotorEncoder[backRight] < x)
		{
			motor[frontRight] = motor[backLeft]  = -speed;
			motor[frontLeft]  = motor[backRight] = speed;
			/*
			if(abs(nMotorEncoder[backRight])>abs(nMotorEncoder[frontRight]))
			{
				motor[frontRight] = motor[backLeft]  = -speed;
				motor[frontLeft]  = motor[backRight] = speed*(1-(abs(nMotorEncoder[frontRight])/abs(nMotorEncoder[backRight])));
			}
			else if(abs(nMotorEncoder[frontRight])==0)
			{
			motor[frontRight] = motor[backLeft]  = -speed;
			motor[frontLeft]  = motor[backRight] = speed;
			}
			else
			{
				motor[frontRight] = motor[backLeft]  = -speed*(1-(abs(nMotorEncoder[backRight])/abs(nMotorEncoder[frontRight])));
				motor[frontLeft]  = motor[backRight] = speed;
			}*/
		}
		break;
	 default:
	   still();
	 }
	 still();
}

//makes the robot turn left (l) or right (r)
void turn(char dir, float angle)
{
	//assume CW/+ and CCW/-
	if(dir!='l' && dir!='r')
		return;

	float scale = (dir=='l')?(1):(-1);
	scale = scale *0.5;
	motor[frontRight] = motor[backRight] = -scale*127;
	motor[frontLeft] = motor[backLeft] = scale*127;

	nMotorEncoder[backLeft] = 0;
	nMotorEncoder[frontLeft] = 0;
	nMotorEncoder[frontRight] = 0;
	nMotorEncoder[backRight] = 0;
	clearDebugStream();

	float encoder_to_angle = 0.21;//183673	//Obtained via testing
	float slow_tolerance = 0.5;	//Percentage of angle at which to start slowing
	//0.2 and 0.0 works for 90*, 0.21 and 0.8 works for 180*

	while(abs(nMotorEncoder[backLeft])*encoder_to_angle<angle*slow_tolerance)
	{
		wait1Msec(10);	//GO FULL SPEED! VALHALLA AWAITS!
	}

	while(abs(nMotorEncoder[backLeft])*encoder_to_angle<angle)
	{
		//Let's start slowing down
		//Motors now go slower as they approach the wanted angle
		float modSpeed = (1.3-((abs(nMotorEncoder[backLeft])*encoder_to_angle)/angle))*127;
		writeDebugStream("modSpeed = %d, %d\n",modSpeed,(((abs(nMotorEncoder[backLeft])*encoder_to_angle)/angle))*127);
		//if(modSpeed < 20) modSpeed = 25;
		motor[frontRight] = motor[backRight] = -scale*modSpeed;
		motor[frontLeft] = motor[backLeft] = scale*modSpeed;
	}
	still();
}

/*allows the robot to move diagonally to the
forward right (fr), forward left (fl)
backward right (br) or backward left (bl)
*/
void diag(string dir, int speed, int time)
{
	//assume CW/+ and CCW/-
	if(strcmp(dir,"fl") == 0)
	{
		motor[frontRight] = motor[backLeft] = -speed;
		motor[backRight] = motor[frontLeft] = 0;
		wait1Msec(time);
	}
	else if (strcmp(dir,"fr") == 0)
	{
		motor[frontRight] = motor[backLeft] = 0;
		motor[backRight] = motor[frontLeft] = -speed;
		wait1Msec(time);
	}
	else if (strcmp(dir,"bl") == 0)
	{
		motor[frontRight] = motor[backLeft] = 0;
		motor[backRight] = motor[frontLeft] = speed;
		wait1Msec(time);
	}
	else if (strcmp(dir,"br") == 0)
	{
		motor[frontRight] = motor[backLeft] = speed;
		motor[backRight] = motor[frontLeft] = 0;
		wait1Msec(time);
	}
	still();
}

//move the arm
void arm(int speed, int distance)
{
	//Left Potentiometer and Right Potentiometer reads
	int LP = SensorValue[LPot];
	int RP = SensorValue[RPot];
	int diff = abs(LP-RP);
	int modSpeed = speed - ((float)diff)/10;
	if(modSpeed < 20)
		modSpeed = 0;
	if(diff < 10)
		modSpeed = speed;

	//Arm moving
	//2000 yields halfway, 3000 yields top, 1250 yields bottom
	while(SensorValue[LPot] < distance)
	{
		if((LP > RP) || (LP < RP))
		{
			motor[armRT] = motor[armRB] = speed;
			motor[armLT] = motor[armLB] = modSpeed;
		}
		//In the case that the right pot equals the left pot,
		//modSpeed is already equal to setSpeed, so nothing is slowed anyway
		else
		{
			motor[armRT] = motor[armRB] = modSpeed;
			motor[armLT] = motor[armLB] = speed;
		}

	}
	while(SensorValue[LPot] > distance)
	{
		if((LP > RP) || (LP < RP))
		{
			motor[armRT] = motor[armRB] = -speed;
			motor[armLT] = motor[armLB] = -modSpeed;
		}
		else
		{
			motor[armRT] = motor[armRB] = -modSpeed;
			motor[armLT] = motor[armLB] = -speed;
		}
	}
	motor[armRT] = motor[armRB] = 0;
	motor[armLT] = motor[armLT] = 0;
}

//close and open the claw
//use a time variable in case the claw
//is not all of the way open/closed. Is
//there a better way to do this?
//limit switch?
//input -1 for close and +1 for open
//500 time = 1/2, 1000 time = 1
void claw(int dir, int time)
{
	motor[LScoop] = motor[RScoop] = dir*128;
	wait1Msec(time);
	motor[LScoop] = motor[RScoop] = 0;
}

task main()
{

//	move('r',40,1000);
//	arm(60,1250);
//	return;
	//turn('l',90);
//	wait1Msec(2000);
//	turn('r',90);
//		wait1Msec(1000);
//		move('f',80,50);
//while(1==1)
//{
//	while(SensorValue[AutoPot] > 2048)//start on right side
//	{
//		side = 1;
//		SensorValue[RLED] = 1;
//		SensorValue[YLED] = 0;
//	}
//	while(SensorValue[AutoPot] < 2048)//start on left side
//	{
//		side = -1;
//		SensorValue[RLED] = 0;
//		SensorValue[YLED] = 1;
//	}
//	side = 0;
	SensorValue[RLED] = 0;
	SensorValue[YLED] = 0;
//}
	arm(60,2500);
	move('f',100,20);
	move('r',100,20);
	move('f',100,30);
	claw(-1,1000);
	move('l',100,1000);
	move('l',100,10);

}
